services:
  url-shortener:
    depends_on:
      - mongo
      - redis
    build:
      context: .
    container_name: url-shortener
    networks:
      - appnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - appnet
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:7.2-alpine
    container_name: redis
    networks:
      - appnet
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379

volumes:
  mongo-data:
  cache:

networks:
  appnet:
